
pipeline{
    agent {
      node {
        label 'slave_1'
      }
    }

    tools {
         maven 'MAVEN_HOME'
         jdk 'JAVA_HOME'
    }

    stages{
       stage('Git Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/GoudSagar/Hello-World-Code.git']]])
            }
        }
        stage('build'){
            steps{
               sh '''
                mvn package
		cp -r webapp/target/webapp.war ${WORKSPACE}/Docker/
                '''
            }
        }
        stage ('Unit Test') {
	        steps {
                echo 'Running Unit Testing'
                sh '''
                mvn test
                '''
             }
         }
  
        stage ('Static Code Analysis') {
             environment {
             scannerHome = tool 'SONAR_SCANNER'
             }
             steps {
                echo 'Running Static Code Analysis'
                 withSonarQubeEnv('SONAR_HOME') {
                 sh '${scannerHome}/bin/sonar-scanner'
                 }
            }
	}
        stage ('Artifact Deploy to Nexus') {
             steps {
                   nexusArtifactUploader(
                   nexusVersion: 'nexus3',
                   protocol: 'http',
                   nexusUrl: '3.145.167.190:8081',
                   groupId: 'org.webapp',
                   version: '1.0-SNAPSHOT',
                   repository: 'maven-snapshots',
                   credentialsId: 'nexus-credentials',
                       artifacts: [
                         [artifactId: 'webapp-app',
                         type: 'war',
                         classifier: '',
                         file: 'webapp/target/webapp.war']
                       ]
                   )
               }
          }
          stage('Docker Build and Push') {
           steps{
               script {
                   withDockerRegistry(credentialsId: 'docker-credentials') {
                      sh "docker build -t goudsagar/webapp-app-tomcat:latest -f Docker/Dockerfile ."
                      sh "docker push goudsagar/webapp-app-tomcat:latest"
                       }
                    }
              }
          } 

	stage('Deploying web application container to Kubernetes') {
           steps {
	       sh '''
                  kubectl apply -f  Docker/deployment.yaml
                  sleep 10
		  kubectl apply -f Docker/service.yaml
                '''
                 }
             }


          
     }
}
