apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: my-replica
spec:
 template:
  metadata:
   name: my-pod
   labels:
    name: nginxpod
    type: frontend
  spec:
   containers:
   - name: nginx-container
     image: nginx:latest
 replicas: 5
 selector:
  matchLabels:
   name: nginxpod
   type: frontend
 
