apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deployment-update
spec:
 template:
  metadata:
   name: my-pod
   labels:
    name: nginxpod
    type: frontend
  spec:
   containers:
   - name: nginx-container
     image: nginx:latest
 replicas: 25
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 1   
 selector:
  matchLabels:
   name: nginxpod
   type: frontend
