apiVersion: v1
kind: Pod
metadata:
 name: my-pod-secret
spec:
 containers:
 - name: nginx-container
   image: nginx:latest
   env:
     - name: USER
       valueFrom:
         secretKeyRef:
           name: my-secret
           key: USERNAME
     - name: PASSWD
       valueFrom:
        secretKeyRef:
          name: my-secret
          key: PASSWORD
