apiVersion: v1
kind: Pod
metadata:
 name: my-pod-vol
spec:
 containers:
 - name: nginx-container
   image: nginx:latest
   volumeMounts:
    - name: hostvol
      mountPath: /app/data
 volumes:
  - name: hostvol 
    hostPath:
     path: /opt/data
