---
- hosts: webservers
  become: true
  gather_facts: no
  tasks:
  - name: Download Tomcat
    get_url: url=https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.43/bin/apache-tomcat-8.5.43.tar.gz dest=/home/ansible
  
  - name: gunzip the file downloaded tomcat file
    command: gunzip apache-tomcat-8.5.43.tar.gz

  - name: Extract the file downloaded tomcat file
    command: tar xvf apache-tomcat-8.5.43.tar
 
  - name: Move the Tomcat directory to a smaller one
    command: mv apache-tomcat-8.5.43 tomcat
  
  - name: Change Ownership and group of the Tomcat directory
    file: path=/home/ansible/tomcat owner=ansible group=ansible mode=775 state=directory recurse=yes
 
  - name: Start Tomcat
    command: nohup /home/ansible/tomcat/bin/startup.sh # Execute command even after you have exited from the shell prompt
    become: true
    become_user: ansible
 
  - name: test the url of tomcat
    uri:
       url: http://18.219.187.161:8080
